from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile
import html
import re


TEMPLATE = Path(r"C:/Users/akank/Downloads/2202113_Akanksha_kumari_.pptx")
OUTPUT = Path("2202113_Akanksha_Kumari_Slashmark_Presentation.pptx")


SLIDES = [
    [
        "COMPANY RESUME ANALYSIS AND IDEAL MATCH FINDER USING PINECONE RAG",
        "DEPARTMENT OF ELECTRICAL ENGINEERING",
        "NATIONAL INSTITUTE OF TECHNOLOGY PATNA",
        "APRIL 2026",
        "PRESENTED BY:",
        "AKANKSHA KUMARI-2202113",
    ],
    [
        "TABLE OF CONTENTS",
        "Introduction",
        "Background of the Study",
        "Problem Statement",
        "Objectives of the Project",
        "Literature Review",
        "Machine Learning Overview",
        "System Architecture",
        "Methodology",
        "Company Document Storage",
        "Resume Data Preprocessing",
        "Feature and Skill Extraction",
        "Pinecone Vector Database",
        "RAG Matching Workflow",
        "Apps Script Automation",
        "Results",
        "Conclusion",
        "Future Scope",
        "References",
    ],
    [
        "INTRODUCTION",
        "Recruitment is an important process for every company.",
        "Companies receive many resumes for every requirement.",
        "Manual resume screening is time-consuming and inconsistent.",
        "This project stores company requirements and candidate resumes.",
        "Both remain active for approximately six months.",
        "Pinecone vector database is used to retrieve ideal matches.",
        "The system recommends candidates with score and potential.",
        "Google Apps Script automates calculation from Forms and Sheets.",
        "The project works as a practical ML engineering solution.",
    ],
    [
        "Background of the Study",
        "Companies often collect resumes through Google Forms, email, and job portals.",
        "Requirement documents contain role details, skills, projects, and company needs.",
        "Traditional systems compare resumes only with keywords.",
        "Modern vector search can compare semantic meaning between documents.",
        "RAG retrieves useful company context before ranking candidate resumes.",
        "This project combines Streamlit, FastAPI, Pinecone, and Apps Script.",
    ],
    [
        "NEED FOR AUTOMATIC RESUME ANALYSIS",
        "Automatic resume analysis is important because:",
        "It reduces manual shortlisting effort.",
        "It helps companies find suitable candidates faster.",
        "It compares resumes with active company requirements.",
        "It gives candidate potential and recommendation reason.",
        "It keeps candidate and company data active for six months.",
        "It supports data-driven recruitment decisions.",
    ],
    [
        "Applications of Resume Matching Systems",
        "Resume matching systems are useful in:",
        ".",
        "Internship hiring programs.",
        "Campus placement shortlisting.",
        "Company recruitment portals.",
        "HR automation using Google Sheets.",
        "Skill-based candidate recommendation.",
        "Talent pool management for future roles.",
    ],
    [
        "OBJECTIVES",
        "The main objectives of this project are:",
        "To build a web app for company requirements and candidate resumes.",
        "To store both data types as active records for six months.",
        "To extract useful text from uploaded PDF files.",
        "To use Pinecone as a vector database.",
        "To implement RAG-style candidate matching.",
        "To automate calculations using Google Apps Script.",
    ],
    [
        "Problem Statement",
        "Companies receive many resumes but cannot review all manually.",
        ".",
        "Company requirements change according to projects and growth.",
        "Old resumes are difficult to reuse for new roles.",
        "Keyword matching alone does not understand candidate potential.",
        "There is a need for an intelligent system that retrieves company context and ranks active resumes.",
    ],
    [
        "Machine Learning Overview",
        "Machine Learning enables systems to learn patterns from data and make predictions.",
        "Key characteristics:",
        "Learns from historical and textual data",
        "Improves decision support",
        "Can handle large document collections",
        "Used in many real-world applications",
        "Examples:",
        "Recommendation systems",
        "Document search",
        "Resume screening",
        "Recruitment analytics",
    ],
    [
        "Types of Machine Learning",
        "Machine learning methods used around this project include:",
        "Supervised Learning",
        "      - Uses labeled examples",
        "      - Useful for score prediction",
        "Unsupervised Learning",
        "      - Finds hidden patterns in text data",
        "Retrieval-Augmented Systems",
        "      - Retrieve relevant context before recommendation",
    ],
    [
        "Literature Review",
        "Several systems use ATS-style resume screening.",
        ".",
        "Early systems used keyword matching and rule-based filters.",
        "Modern systems use NLP to extract skills and sections.",
        "Vector databases improve semantic document search.",
        "RAG systems combine retrieval with explainable recommendations.",
        "Google Apps Script supports low-cost workflow automation.",
    ],
    [
        "Factors Affecting Candidate Match",
        "Candidate match depends on multiple factors.",
        "Technical Factors",
        "Required programming skills",
        "Tools and frameworks",
        "Project experience",
        "Profile Factors",
        "Education and internship experience",
        "Communication skills",
        "Role alignment",
    ],
    [
        "Company and Requirement Factors",
        "Matching also depends on company context.",
        "Company Factors",
        "Growth direction",
        "Technology stack",
        "Current projects",
        "Requirement Factors",
        "Job role",
        "Required skills",
        "Expected responsibilities",
    ],
    [
        "Proposed System",
        "The proposed system uses ML and RAG concepts for resume matching.",
        "Key components:",
        "Company document upload",
        "Candidate resume upload",
        "Text extraction and preprocessing",
        "Pinecone vector storage",
        "RAG-based ideal match recommendation",
    ],
    [
        "System Architecture",
        "The system architecture consists of several modules.",
        ".",
        "Streamlit Dashboard",
        "Candidate Resume Module",
        "Company Document Module",
        "FastAPI Backend",
        "Pinecone Vector Database",
        "Google Apps Script Automation",
    ],
    [
        "Methodology",
        "The methodology followed in this project includes:",
        "Collect company requirement documents",
        "Collect candidate resumes",
        "Extract and clean PDF text",
        "Generate vector representations",
        "Store vectors with metadata in Pinecone",
        "Retrieve context and rank candidates",
        "Return score, potential, and recommendation",
    ],
    [
        "Company Document Description",
        "Company documents can contain information related to:",
        "Current hiring requirements",
        "Company establishment and growth",
        "Technology stack",
        "Project details",
        "Department needs",
        "Culture and soft-skill expectations",
        "These records are stored as company_knowledge vectors.",
    ],
    [
        "Resume Data Preprocessing",
        "Resume preprocessing improves document quality.",
        "Steps include:",
        "PDF text extraction",
        "Whitespace cleaning",
        "Tokenization",
        "Section detection",
        "Skill identification",
        "Keyword comparison",
    ],
    [
        "Feature and Skill Extraction",
        "The system extracts useful information from resumes.",
        "Important extracted features:",
        "Education section",
        "Experience and internships",
        "Projects",
        "Technical skills",
        "Contact details",
        "Missing job-related skills",
    ],
    [
        "Pinecone Vector Database",
        "Pinecone is used as the vector database.",
        "It stores candidate_resume and company_knowledge records.",
        "Candidate vectors represent resume content.",
        "Company vectors represent requirement and growth documents.",
        "Metadata filters retrieve only active records.",
        "The active duration is approximately six months.",
    ],
    [
        "RAG Workflow",
        "RAG means Retrieval-Augmented Generation.",
        "Step 1: User enters company requirement.",
        "Step 2: Relevant company context is retrieved.",
        "Step 3: Requirement is augmented with retrieved context.",
        "Step 4: Active candidate resumes are retrieved.",
        "Step 5: Recommendation and potential are generated.",
    ],
    [
        "Candidate Potential Categories",
        "The system classifies candidates into categories:",
        "Ideal Match",
        "      - High score and low skill gap",
        "Strong Potential",
        "      - Good candidate for shortlist",
        "Moderate Potential",
        "      - Backup or training candidate",
        "Low Match",
        "      - Not prioritized for current requirement",
    ],
    [
        "Apps Script Automation",
        "Google Apps Script automates the workflow.",
        "Candidate form sends resumes to /ingest.",
        "Company form sends requirements to /company-ingest.",
        "Google Sheets menu calls /rag-match.",
        "The sheet receives best candidate, potential, score, and recommendation.",
        "This makes the system easy for HR users.",
    ],
    [
        "FastAPI Backend",
        "FastAPI provides automation endpoints.",
        "Main endpoints:",
        "/health",
        "/ingest",
        "/company-ingest",
        "/rag-match",
        "These endpoints allow Forms and Sheets to use the same matching engine.",
    ],
    [
        "Streamlit Dashboard",
        "The dashboard contains multiple tabs:",
        "Resume Check",
        "Candidate Upload",
        "Company Documents",
        "Auto Match",
        "Stored Data",
        "Apps Script Setup",
        "It provides a complete user workflow.",
    ],
    [
        "Deployment",
        "The project is deployment-ready.",
        "GitHub stores the source code.",
        "Streamlit Cloud deploys the dashboard.",
        "Render can deploy the FastAPI backend.",
        "Pinecone stores vectors in the cloud.",
        "Environment variables store API keys securely.",
    ],
    [
        "Results",
        "The system successfully performs:",
        "Resume upload and text extraction",
        "Company requirement storage",
        "Six-month active data management",
        "Vector retrieval using Pinecone",
        "RAG-style candidate recommendation",
        "CSV shortlist export",
    ],
    [
        "Testing",
        "The project was tested using sample resumes and requirements.",
        "Python syntax checks passed.",
        "RAG smoke test generated candidate potential.",
        "Streamlit app ran locally.",
        "GitHub repository was pushed successfully.",
        "Report and PPT files were generated.",
    ],
    [
        "Advantages",
        "The proposed system has several advantages:",
        "Reduces manual resume screening time",
        "Uses company context for better matching",
        "Maintains active candidate pool for six months",
        "Supports automation using Google Sheets",
        "Works with Pinecone and local fallback",
        "Provides explainable recommendations",
    ],
    [
        "Limitations",
        "Some limitations of the project are:",
        "Image-only PDFs may not extract text correctly.",
        "Current embeddings are lightweight for easy deployment.",
        "Pinecone requires API keys for production use.",
        "The system needs authentication for real company use.",
        "Skill bank can be expanded in future.",
    ],
    [
        "Future Scope",
        "Future improvements can include:",
        "Transformer-based embeddings",
        "Login and role-based access",
        "Email alerts for ideal matches",
        "Interview scheduling",
        "Advanced analytics dashboard",
        "Integration with job portals",
    ],
    [
        "Conclusion",
        "The project implements a company resume analysis and ideal match finder.",
        "It stores company documents and candidate resumes for six months.",
        "Pinecone enables vector search.",
        "RAG improves recommendation using company context.",
        "Apps Script provides automatic calculation.",
        "The project is useful as a real-world ML engineering application.",
    ],
    [
        "References",
        "Streamlit Documentation",
        "FastAPI Documentation",
        "Pinecone Documentation",
        "Google Apps Script Documentation",
        "pypdf Documentation",
        "GitHub Repository:",
        "https://github.com/akanksha29122002/company_Resume_analysis",
    ],
    [
        "THANK YOU",
        "Presented by:",
        "Akanksha Kumari",
        "Roll No: 2202113",
        "Department of Electrical Engineering",
        "National Institute of Technology Patna",
        "Project Domain: Machine Learning Internship",
    ],
]


def replace_text_nodes(xml, new_texts):
    index = 0

    def repl(match):
        nonlocal index
        if index < len(new_texts):
            value = html.escape(new_texts[index])
        else:
            value = ""
        index += 1
        return f"<a:t>{value}</a:t>"

    return re.sub(r"<a:t>.*?</a:t>", repl, xml)


def build():
    with ZipFile(TEMPLATE, "r") as zin, ZipFile(OUTPUT, "w", ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            match = re.match(r"ppt/slides/slide(\d+)\.xml$", item.filename)
            if match:
                slide_number = int(match.group(1))
                if 1 <= slide_number <= len(SLIDES):
                    xml = data.decode("utf-8", "ignore")
                    data = replace_text_nodes(xml, SLIDES[slide_number - 1]).encode("utf-8")
            zout.writestr(item, data)
    print(OUTPUT.resolve())


if __name__ == "__main__":
    build()
